### ISSUE TITLE
Choix du kakémono

### ISSUE THREAD

**Issue by yjacolin** [OSGeo-fr/communication#5]
![osgeo_qgis](https://cloud.githubusercontent.com/assets/660191/20298915/b4106264-ab18-11e6-9cd3-271a3228ba4b.png)
![osgeo_qgis_green](https://cloud.githubusercontent.com/assets/660191/20298916/b413f4ec-ab18-11e6-9d68-726e8d33353f.png)
![osgeo_qgis_white](https://cloud.githubusercontent.com/assets/660191/20298917/b4158582-ab18-11e6-8abb-62eae6b6fe3d.png)

**Comment by luckgentilpiron** [comment]
+1 pour la proposition numéro 2 !

**Comment by haubourg** [comment]
-1 sur le premier, trop de jaune
+1 sur le deuxième avec fond vert
+0 sur le troisèle, plus light mais qui met bien en valeur l'osgeo fr

**Comment by simogeo** [comment]
- 1 pour la première
+ 0 pour la deuxième
+ 1 pour la 3éme - plus sobre

**Comment by ThomasG77** [comment]
+0 pour le 1er
+0 pour le 2ème
+1 pour le troisième

**Comment by yjacolin** [comment]
+1 pour le vert, +0 pour le blanc et -1 pour le jaune

**Comment by yjacolin** [comment]
Résultat (avec les votes de la liste) :
* vert : 5 * +1, 2 * +0, aucun rejet
* blanc : 4 * +1, 3 * +0, aucun rejet
* jaune : 1 * +0, 1 * -0 et 4 rejets

Le vert a une légère avance. Merci pour vos retours.
